### ISSUE TITLE
Error with DASH Cannot find name 'OfflineStreamEvent'

### ISSUE THREAD

**Issue by arcovoltaico** [flocasts/flo-angular#233]
Following install instructions I am getting this error when running the angular 9 app.
```
ERROR in node_modules/dashjs/build/typings/index.d.ts:198:18 - error TS2304: Cannot find name 'OfflineStreamEvent'.

198         on(type: OfflineStreamEvent['type'], listener: (e: OfflineStreamEvent) => void, scope?: object): void;
```

Although the problem is on the dependency : https://github.com/Dash-Industry-Forum/dash.js/issues/3261

**Comment by patrickmichalina** [comment]
@arcovoltaico have you tried pinning dash library to `3.0.0`?

**Comment by arcovoltaico** [comment]
> @arcovoltaico have you tried pinning dash library to `3.0.0`?

Thanks! It works with 3.0.0, so I guess for now it's ok as provisional solution.
